### ISSUE TITLE
Trying to access non-existent cores

### ISSUE THREAD

**Issue by kevihiiin** [erpalma/lenovo-throttling-fix#22]
When trying to run this fix on an X1 Carbon 6th gen I get the following error:

> Traceback (most recent call last):
  File "/usr/lib/lenovo-throttling-fix/lenovo_fix.py", line 245, in <module>
    main()
  File "/usr/lib/lenovo-throttling-fix/lenovo_fix.py", line 205, in main
    undervolt(config)
  File "/usr/lib/lenovo-throttling-fix/lenovo_fix.py", line 78, in undervolt
    writemsr(0x150, calc_undervolt_msr(plane, config.getfloat('UNDERVOLT', plane)))
  File "/usr/lib/lenovo-throttling-fix/lenovo_fix.py", line 60, in writemsr
    raise e
  File "/usr/lib/lenovo-throttling-fix/lenovo_fix.py", line 51, in writemsr
    f = os.open(c, os.O_WRONLY)
OSError: [Errno 6] No such device or address: '/dev/cpu/15/msr'

The skript was installed from the AUR and I am running it on an `X1 Carbon i7-8550U`, Manjaro Kernel `4.17.9-1-MANJARO`

It seems like the skript tries to access the msr register for cpu core number 15, which should not exist on a 8 core machine.
If I can help in any way, please let me know!

**Comment by kevihiiin** [comment]
After some digging I found that other people had similar issues:
[Georgewhewell's undervolt issue](https://github.com/georgewhewell/undervolt/issues/12) and the [solution](https://github.com/georgewhewell/undervolt/pull/17/files)
The solution by freesamael uses the `multiprocessing.cpu_count()` function to get the cpu entries.

I tried something similar and it fixed my issue.
