### ISSUE TITLE
Additional installation requirement--Fedora 28

### ISSUE THREAD

**Issue by Laekius** [erpalma/lenovo-throttling-fix#53]
Attempted install on a brand new Fedora 28 system (Thinkpad T480s) after installing all listed dependencies. Installation failed sighting "No module named 'cairo'. Adding the python3-cairo-devel package resolved this issue.

**Comment by erpalma** [comment]
Thank you!

**Comment by brandex007** [comment]
I get the following error during install: "ModuleNotFoundError: No module named 'cairo'"

**Comment by janzeleny** [comment]
Same here. I get the traceback below but the installation seems to have finished and the service is running afterwards. Starting /opt/lenovo_fix/venv/bin/python3 manually and importing cairo there works though.

> Building wheels for collected packages: configparser, dbus-python, PyGObject, pycairo
>   Running setup.py bdist_wheel for configparser ... done
>   Stored in directory: /root/.cache/pip/wheels/a3/61/79/424ef897a2f3b14684a7de5d89e8600b460b89663e6ce9d17c
>   Running setup.py bdist_wheel for dbus-python ... done
>   Stored in directory: /root/.cache/pip/wheels/77/5f/68/8feca31b06e015a95fc463f93bcbf1228f6937f34f354ca60c
>   Running setup.py bdist_wheel for PyGObject ... error
>   Complete output from command /opt/lenovo_fix/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cikw6qmv/PyGObject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-d8eu2he9 --python-tag cp36:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-x86_64-3.6
>   creating build/lib.linux-x86_64-3.6/pygtkcompat
>   copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.6/pygtkcompat
>   copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.6/pygtkcompat
>   copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.6/pygtkcompat
>   creating build/lib.linux-x86_64-3.6/gi
>   copying gi/_error.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_option.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/docstring.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/module.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_constants.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/__init__.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_compat.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/importer.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.6/gi
>   copying gi/types.py -> build/lib.linux-x86_64-3.6/gi
>   creating build/lib.linux-x86_64-3.6/gi/repository
>   copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.6/gi/repository
>   creating build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.6/gi/overrides
>   running build_ext
>   pycairo: new API
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 1189, in <module>
>       main()
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 1184, in main
>       zip_safe=False,
>     File "/opt/lenovo_fix/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
>       return distutils.core.setup(**attrs)
>     File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
>       self.run_command(cmd)
>     File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/opt/lenovo_fix/venv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
>       self.run_command('build')
>     File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 1024, in run
>       self._setup_extensions()
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 1019, in _setup_extensions
>       add_pycairo(gi_cairo_ext)
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 1003, in add_pycairo
>       ext.include_dirs += [get_pycairo_include_dir()]
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 832, in get_pycairo_include_dir
>       include_dir = find_path(find_new_api())
>     File "/tmp/pip-install-cikw6qmv/PyGObject/setup.py", line 777, in find_new_api
>       import cairo
>   ModuleNotFoundError: No module named 'cairo'
>   
>   ----------------------------------------
>   Failed building wheel for PyGObject
>

**Comment by erpalma** [comment]
Yes, that's a bit weird. I think this is a pygobject setup.py bug. Can you please try:
```
cd /tmp
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install pip configparser dbus-python pycairo pygobject --no-cache-dir --force-reinstall --no-binary ':all:'
```
I think this should work.

**Comment by brandex007** [comment]
@erpalma 
I get the following error on the last command:
`Command "/tmp/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-uct7nbmn/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xyl7k73d/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/venv/include/site/python3.7/dbus-python" failed with error code 1 in /tmp/pip-install-uct7nbmn/dbus-python/`

**Comment by erpalma** [comment]
Hmm strange. BTW even if you get `ModuleNotFoundError` the installation is still successful.

**Comment by Xplosm** [comment]
Since I benefit from this tool I'd like to maintain a Fedora Copr repo so the installation is easier for Red Hat/Fedora users if you are OK with it.

I only need a way to consistently get your compressed file where only the version iterations change. I know GitHub provides that but I don't know the URL needed and I'd like to work with you on that front.

Thanks,
O

**Comment by hobindar** [comment]
@brandex007 Make sure you have `python-devel` installed first: `sudo dnf install python-devel`.
